version: "3"

volumes:
    db:

services:
  worker: &worker
    build:
      context: .
      dockerfile: ./dockerfiles/local/Dockerfile
    env_file:
      - .env/.local/django
    depends_on:
      - db
      - redis
    command: celery -A csv_processor worker -B -l debug
    volumes:
      - ./media:/app/media
      - ./csv_processor:/app/csv_processor
      - ./pytest.ini:/app/pytest.ini
    networks:
      - default

  web:
    <<: *worker
    command: >
      sh -c "urlwait &&
               ./manage.py migrate &&
               gunicorn csv_processor.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker"
    ports:
      - "8100:8000"
      - "587:587"
    networks:
      default:

  db:
    image: postgres:12
    env_file:
      - .env/.local/postgres
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:latest
