# Generated by Django 3.2 on 2022-05-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("name", "first_name", "email"), name="name_email_idx"
            ),
        ),
    ]
